'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type ExampleInputCustomEvent } from "@example/stencil-lib";
import { ExampleInput as ExampleInputElement, defineCustomElement as defineExampleInput } from "@example/stencil-lib/components/example-input.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

export type ExampleInputEvents = {
    onExampleChange: EventName<ExampleInputCustomEvent<string>>,
    onExampleFocus: EventName<ExampleInputCustomEvent<void>>,
    onExampleBlur: EventName<ExampleInputCustomEvent<void>>
};

export const ExampleInput: StencilReactComponent<ExampleInputElement, ExampleInputEvents> = /*@__PURE__*/ createComponent<ExampleInputElement, ExampleInputEvents>({
    tagName: 'example-input',
    elementClass: ExampleInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onExampleChange: 'exampleChange',
        onExampleFocus: 'exampleFocus',
        onExampleBlur: 'exampleBlur'
    } as ExampleInputEvents,
    defineCustomElement: defineExampleInput
});
