/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

// @ts-ignore - ignore potential type issues as the project is importing itself
import { type ExampleInputCustomEvent } from "@example/stencil-lib";
import * as clientComponents from '@example/stencil-lib-react';
import { ExampleInput as ExampleInputElement } from "@example/stencil-lib/components/example-input.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, type HydrateModule, type ReactWebComponent, type SerializeShadowRootOptions } from '@stencil/react-output-target/ssr';

export const serializeShadowRoot: SerializeShadowRootOptions = { "default": "declarative-shadow-dom" };

export type ExampleInputEvents = {
    onExampleChange: EventName<ExampleInputCustomEvent<string>>,
    onExampleFocus: EventName<ExampleInputCustomEvent<void>>,
    onExampleBlur: EventName<ExampleInputCustomEvent<void>>
};

export const ExampleInput: StencilReactComponent<ExampleInputElement, ExampleInputEvents> = /*@__PURE__*/ createComponent<ExampleInputElement, ExampleInputEvents>({
    tagName: 'example-input',
    properties: {
        value: 'value',
        placeholder: 'placeholder',
        disabled: 'disabled'
    },
    hydrateModule: import('@example/stencil-lib/hydrate') as Promise<HydrateModule>,
    clientModule: clientComponents.ExampleInput as ReactWebComponent<ExampleInputElement, ExampleInputEvents>,
    serializeShadowRoot
});
